services:
  bunker-ia:
    build: .
    container_name: bunker-jorge
    restart: always
    env_file:
      - .env  # Esta linha faz a ponte entre o seu arquivo de segredos e o container
    ports:
      - "2222:22"       # SSH
      - "3100:3100"     # Paperclip / OpenCode Web
      - "3101:3101"     # Paperclip Gateway
      - "8081:8081"     # Filebrowser
      - "8082:8082"     # code-server
      - "9119:9119"     # Hermes Dashboard
    volumes:
      - jorge-home:/home/jorge
      - tailscale-data:/var/lib/tailscale
      - paperclip-data:/home/jorge/.paperclip # Persistência do Paperclip e Postgres
    cap_add:
      - NET_ADMIN # Necessário para o Tailscale
    devices:
      - /dev/net/tun:/dev/net/tun # Necessário para o Tailscale

volumes:
  jorge-home:
  tailscale-data:
  paperclip-data:
